  @startuml

    |Менеджер|
    start
    :Натискає кнопку \n"Create poll request";
    |Система|
    :Пропонує форму \n"New poll request";
    |Менеджер|
    :Менеджер заповнює \nполе "Message";
    :Менеджер натискає \nкнопку "Send request";
    |Система|
    :Система надсилає \nзапит аналітику;
    |Менеджер|
    stop

@enduml
