@startuml

    |Менеджер|
    start
    :Натискає кнопку "Create poll request";
    |Система|
    :Пропонує форму "New poll request";
    |Менеджер|
    :Менеджер заповнює поле "Message";
    :Менеджер натискає кнопку "Send request";
    |Система|
    :Система надсилає запит аналітику;
    |Менеджер|
    stop

@enduml
