-- MySQL Script generated by MySQL Workbench
-- Tue Dec  1 09:32:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL,
  `name` TEXT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Survey` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Survey` (
  `id` INT NOT NULL,
  `name` TEXT NOT NULL,
  `topic` TEXT NOT NULL,
  `deadline` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `id` INT NOT NULL,
  `type` INT NOT NULL,
  `text` TEXT NOT NULL,
  `Survey_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Survey_id`),
  INDEX `fk_Question_Survey_idx` (`Survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Survey`
    FOREIGN KEY (`Survey_id`)
    REFERENCES `mydb`.`Survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Expert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Expert` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Expert` (
  `id` INT NOT NULL,
  `occupation` TEXT NOT NULL,
  `userid` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_Expert_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Expert_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `text` TEXT NULL,
  `Expert_id` INT NOT NULL,
  `Question_id` INT NOT NULL,
  `Question_Survey_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Expert_id`, `Question_id`, `Question_Survey_id`),
  INDEX `fk_Answer_Expert1_idx` (`Expert_id` ASC) VISIBLE,
  INDEX `fk_Answer_Question1_idx` (`Question_id` ASC, `Question_Survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_Expert1`
    FOREIGN KEY (`Expert_id`)
    REFERENCES `mydb`.`Expert` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`Question_id` , `Question_Survey_id`)
    REFERENCES `mydb`.`Question` (`id` , `Survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PossibleAnswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PossibleAnswers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PossibleAnswers` (
  `id` INT NOT NULL,
  `text` TEXT NOT NULL,
  `Question_id` INT NOT NULL,
  `Question_Survey_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Question_id`, `Question_Survey_id`),
  INDEX `fk_PossibleAnswers_Question1_idx` (`Question_id` ASC, `Question_Survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_PossibleAnswers_Question1`
    FOREIGN KEY (`Question_id` , `Question_Survey_id`)
    REFERENCES `mydb`.`Question` (`id` , `Survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
