-- MySQL Script generated by MySQL Workbench
-- Mon Dec  7 12:26:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SurvExp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SurvExp` ;

-- -----------------------------------------------------
-- Schema SurvExp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SurvExp` DEFAULT CHARACTER SET utf8 ;
USE `SurvExp` ;

-- -----------------------------------------------------
-- Table `SurvExp`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SurvExp`.`User` ;

CREATE TABLE IF NOT EXISTS `SurvExp`.`User` (
  `id` INT NOT NULL,
  `name` TEXT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SurvExp`.`Survey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SurvExp`.`Survey` ;

CREATE TABLE IF NOT EXISTS `SurvExp`.`Survey` (
  `id` INT NOT NULL,
  `name` TEXT NOT NULL,
  `topic` TEXT NOT NULL,
  `deadline` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SurvExp`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SurvExp`.`Question` ;

CREATE TABLE IF NOT EXISTS `SurvExp`.`Question` (
  `id` INT NOT NULL,
  `type` INT NOT NULL,
  `text` TEXT NOT NULL,
  `Survey_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Survey_id`),
  INDEX `fk_Question_Survey_idx` (`Survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Survey`
    FOREIGN KEY (`Survey_id`)
    REFERENCES `SurvExp`.`Survey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SurvExp`.`Expert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SurvExp`.`Expert` ;

CREATE TABLE IF NOT EXISTS `SurvExp`.`Expert` (
  `id` INT NOT NULL,
  `occupation` TEXT NOT NULL,
  `userid` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_Expert_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Expert_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `SurvExp`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SurvExp`.`Answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SurvExp`.`Answer` ;

CREATE TABLE IF NOT EXISTS `SurvExp`.`Answer` (
  `id` INT NOT NULL,
  `date` DATE NOT NULL,
  `text` TEXT NULL,
  `Expert_id` INT NOT NULL,
  `Question_id` INT NOT NULL,
  `Question_Survey_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Expert_id`, `Question_id`, `Question_Survey_id`),
  INDEX `fk_Answer_Expert1_idx` (`Expert_id` ASC) VISIBLE,
  INDEX `fk_Answer_Question1_idx` (`Question_id` ASC, `Question_Survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_Expert1`
    FOREIGN KEY (`Expert_id`)
    REFERENCES `SurvExp`.`Expert` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`Question_id` , `Question_Survey_id`)
    REFERENCES `SurvExp`.`Question` (`id` , `Survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SurvExp`.`PossibleAnswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SurvExp`.`PossibleAnswers` ;

CREATE TABLE IF NOT EXISTS `SurvExp`.`PossibleAnswers` (
  `id` INT NOT NULL,
  `text` TEXT NOT NULL,
  `Question_id` INT NOT NULL,
  `Question_Survey_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Question_id`, `Question_Survey_id`),
  INDEX `fk_PossibleAnswers_Question1_idx` (`Question_id` ASC, `Question_Survey_id` ASC) VISIBLE,
  CONSTRAINT `fk_PossibleAnswers_Question1`
    FOREIGN KEY (`Question_id` , `Question_Survey_id`)
    REFERENCES `SurvExp`.`Question` (`id` , `Survey_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SurvExp`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `SurvExp`;
INSERT INTO `SurvExp`.`User` (`id`, `name`, `role`) VALUES (1, 'Andrew', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `SurvExp`.`Survey`
-- -----------------------------------------------------
START TRANSACTION;
USE `SurvExp`;
INSERT INTO `SurvExp`.`Survey` (`id`, `name`, `topic`, `deadline`) VALUES (1, 'Оценка служб такси', 'Сфера услуг', '20-12-2020');
INSERT INTO `SurvExp`.`Survey` (`id`, `name`, `topic`, `deadline`) VALUES (2, 'Использование мобильных устройств', 'ИТ', '31-12-2020');

COMMIT;

