@startuml
  
  '-----Пользователи-----'
  '-Пользователь-'
  entity User
  entity User.id
  entity User.username
  entity User.role
  '-Эксперт-'
  entity Expert
  entity Expert.id
  entity Expert.occupation
  
  '-----Объекты-----'
  '-Опрос-'
  entity Survey
  entity Survey.id
  entity Survey.name
  entity Survey.topic
  entity Survey.deadline
  '-Вопрос-'
  entity Question
  entity Question.id
  entity Question.type
  entity Question.text
  '-Ответы на анкеты-'
  entity Answer
  entity Answer.id
  entity Answer.date
  entity Answer.text
  '-Возможные ответы-'
  entity PossibleAnswers
  entity PossibleAnswers.id
  entity PossibleAnswers.text
  '-Типы вопросов-'
  entity QuestionType
  entity QuestionType.id
  entity QuestionType.name
  '-Роли-'
  entity Role
  entity Role.id
  entity Role.name

  
  '-----Пользователи-----'
  '-Пользователь-'
  User.id -u-* User
  User.username -u-* User
  User.role -u-* User
  '-Эксперт-'
  Expert.id -d-* Expert
  Expert.occupation -d-* Expert
  
  '-----Объекты-----'
  '-Связи-'
  Question "0, *" -u- "1, 1" Survey
  User "1, 1" -u- "0, 1" Expert
  Answer "0, *" -u- "1, 1" Question
  Answer "0, *" -u- "1, 1" Expert
  PossibleAnswers "0, *" -u- "1, 1" Question
  QuestionType "1, 1" -u- "1, 1" Question
  Role "1, 1" -u- "1, 1" User
  '-Опрос-'
  Survey.id -d-* Survey
  Survey.name -d-* Survey
  Survey.topic -d-* Survey
  Survey.deadline -d-* Survey
  '-Вопрос-'
  Question.id -u-* Question
  Question.type -u-* Question
  Question.text -u-* Question
  '-Ответы на анкеты-'
  Answer.id -u-* Answer
  Answer.date -u-* Answer
  Answer.text -u-* Answer
  '-Возможные ответы-'
  PossibleAnswers.id -u-* PossibleAnswers
  PossibleAnswers.text -u-* PossibleAnswers
  '-Типы вопросов-'
  QuestionType.id -u-* QuestionType
  QuestionType.name -u-* QuestionType
  '-Роли-'
  Role.id -u-* Role
  Role.name -u-* Role

@enduml
