@startuml
  
  '-----Пользователи-----'
  '-Пользователь-'
  entity Users
  entity Users.id
  entity Users.Usersname
  entity Users.Roles
  '-Эксперт-'
  entity Experts
  entity Experts.id
  entity Experts.occupation
  
  '-----Объекты-----'
  '-Опрос-'
  entity Surveys
  entity Surveys.id
  entity Surveys.name
  entity Surveys.topic
  entity Surveys.deadline
  '-Вопрос-'
  entity Questions
  entity Questions.id
  entity Questions.type
  entity Questions.text
  '-Ответы на анкеты-'
  entity Answers
  entity Answers.id
  entity Answers.date
  entity Answers.text
  '-Возможные ответы-'
  entity PossibleAnswers
  entity PossibleAnswers.id
  entity PossibleAnswers.text
  '-Типы вопросов-'
  entity QuestionTypes
  entity QuestionTypes.id
  entity QuestionTypes.name
  '-Роли-'
  entity Roles
  entity Roles.id
  entity Roles.name

  
  '-----Пользователи-----'
  '-Пользователь-'
  Users.id -u-* Users
  Users.Usersname -u-* Users
  Users.Roles -u-* Users
  '-Эксперт-'
  Experts.id -d-* Experts
  Experts.occupation -d-* Experts
  
  '-----Объекты-----'
  '-Связи-'
  Questions "0, *" -u- "1, 1" Surveys
  Answers "0, *" -u- "1, 1" Questions
  Answers "1, 1" -u- "0, *" Experts
  Questions "1, 1" -u- "0, *" PossibleAnswers
  QuestionTypes "1, 1" -u- "1, 1" Questions
  Roles "1, 1" -u- "1, 1" Users
  Experts "0, *" -u- "1, 1" Users
  '-Опрос-'
  Surveys.id -d-* Surveys
  Surveys.name -d-* Surveys
  Surveys.topic -d-* Surveys
  Surveys.deadline -d-* Surveys
  '-Вопрос-'
  Questions.id -u-* Questions
  Questions.type -u-* Questions
  Questions.text -u-* Questions
  '-Ответы на анкеты-'
  Answers.id -u-* Answers
  Answers.date -u-* Answers
  Answers.text -u-* Answers
  '-Возможные ответы-'
  PossibleAnswers.id -u-* PossibleAnswers
  PossibleAnswers.text -u-* PossibleAnswers
  '-Типы вопросов-'
  QuestionTypes.id -u-* QuestionTypes
  QuestionTypes.name -u-* QuestionTypes
  '-Роли-'
  Roles.id -u-* Roles
  Roles.name -u-* Roles

@enduml
