@startuml

  entity Users <<ENTITY>> {
    id:INT
    Usersname:TEXT
    Roles:INT
  }
  
  entity Experts <<ENTITY>>{
    id:INT
    occupation:TEXT
  }
  
  entity Surveys <<ENTITY>>{
    id:INT
    name:TEXT
    topic:TEXT
    deadline:DATE
  }
  
  entity Questions <<ENTITY>>{
    id:INT
    type:INT
    text:TEXT
  }

  entity Answers <<ENTITY>> {
    id:INT
    date:DATE
    text:TEXT
  }
  
  entity PossibleAnswers <<ENTITY>> {
    id:INT
    text:TEXT
  }

  entity QuestionTypes <<ENTITY>> {
    id:INT
    name:TEXT
  }

  entity Roles <<ENTITY>> {
  	id:INT
  	name:TEXT
  }

  Questions "0, *" -u- "1, 1" Surveys
  Answers "0, *" -u- "1, 1" Questions
  Answers "1, 1" -u- "0, *" Experts
  Questions "1, 1" -u- "0, *" PossibleAnswers
  QuestionTypes "1, 1" -u- "1, 1" Questions
  Roles "1, 1" -u- "1, 1" Users
  Experts "0, *" -u- "1, 1" Users
      
@enduml
