@startuml

  entity User <<ENTITY>> {
    id:INT
    username:TEXT
    role:INT
  }
  
  entity Expert <<ENTITY>>{
    id:INT
    occupation:TEXT
  }
  
  entity Survey <<ENTITY>>{
    id:INT
    name:TEXT
    topic:TEXT
    deadline:DATE
  }
  
  entity Question <<ENTITY>>{
    id:INT
    type:INT
    text:TEXT
  }

  entity Answer <<ENTITY>> {
    id:INT
    date:DATE
    text:TEXT
  }
  
  entity PossibleAnswers <<ENTITY>> {
    id:INT
    text:TEXT
  }

  Question "1, *" -u- "1, 1" Survey
  User "1, 1" -u- "1, 1" Expert
  Answer "1, 1" -u- "1, 1" Question
  Answer "0, *" -u- "1, 1" Expert
  Question "1, 1" -u- "0, *" PossibleAnswers
      
@enduml
